centreon:
  image: paperinik/rpi-centreon:latest
  ports:
   - "9412:22"
   - "9413:443"
   - "9410:8080"
  volumes:
   - /home/pi/docker_path/centreon/log:/var/log/centreon
  links:
   - mysql
  privileged: true
mysql:
  image: hypriot/rpi-mysql:latest
  ports:
   - "9415:3306"
  volumes:
   - /home/pi/docker_path/mysql/data:/var/lib/mysql
   - /home/pi/docker_path/mysql/etc/my.cnf:/etc/mysql/my.cnf
  environment:
     - MYSQL_ROOT_PASSWORD=root
