centreon:
  build: centreon-docker/
  ports:
   - "2222:22"
   - "1443:443"
   - "8080:8080"
  volumes:
   - /var/log/centreon:/var/log/centreon
  links:
   - mysql
  privileged: true
mysql:
  image: mariadb:latest
  ports:
   - "13306:3306"
  volumes:
   - /var/lib/centreon/mysql:/var/lib/mysql
   - /var/log/mysqld.log:/var/log/centreon/mysqld.log
  environment:
     - MYSQL_ROOT_PASSWORD=c3ntreon007pw
